@FluentValidationDemo_HostAddress = http://localhost:5236

GET {{FluentValidationDemo_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{FluentValidationDemo_HostAddress}}/api/personas
Accept: application/json
Content-Type: application/json

{
    "nombre": "Felipe",
    "email": "felipe@hotmail.com",
    "edad": 99,
    "fechaInicial": "2024-01-01",
    "fechaFinal": "2025-01-01"
}